FROM docker.artifactory.omnisys.local/python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y \
    catdoc \
    libxml2-dev \
    libxslt-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic

COPY app /app/app

EXPOSE 8000
CMD bash -lc "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
